# Generated by Django 6.0.3 on 2026-03-12 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[a-zA-Z0-9_]+$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
