# Generated by Django 6.0.3 on 2026-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Action', 'Action'), ('Information', 'Information'), ('Risk', 'Risk'), ('Update', 'Update')], max_length=20)),
                ('description', models.TextField()),
                ('publishing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
