# Generated by Django 6.0.3 on 2026-03-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_handover', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
