# Generated by Django 6.0.3 on 2026-03-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_handover', '0002_rename_created_date_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('cpp', 'C++'), ('other', 'Other')], default='other'),
        ),
    ]
