# Generated by Django 6.0.3 on 2026-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_handover', '0002_ticketstatushistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
